volumes:
  pgdata:

services:
  postgres:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  django:
    build: .
    env_file: .env
    ports:
      - "80:8000"
    depends_on:
      - postgres
